# Exercise: Config and Deployment
configure_infrastructure: 
  docker:
    - image: 
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["00:a7:e4:e3:8c:e1:c3:ef:84:bb:95:2c:c3:5e:27:a0"] 
    - run:
        name: Install Ansible
        command: |
          apk add --update ansible
          


    - run:
        name: Run Playbook and Configure server
        command: |
          # Your command
          ansible-playbook -i [inventory-file] [playbook-file]